### ISSUE TITLE
Build crashes on windows x64 in common.cpp

### ISSUE THREAD

**Issue by Andy608** [dalerank/nanogui#10]
Hello, when I run example1.cpp right now, it crashes when getting the cFileName variable. The FirstFindFileA() function seems to be the cause of this since it's returning an incorrect value.

![Capture](https://user-images.githubusercontent.com/7517525/74461780-18030e80-4e5d-11ea-9fd3-6b450100af2e.png)

Please let me know if you are aware of this issue and/or if you will be providing a fix soon.

*Edit - Using Vulkan backend.

Thanks,
Andrew

**Comment by dalerank** [comment]
seems crashed because files not found, will try fix it... also you can fix it too

**Comment by Andy608** [comment]
Thanks for the fast reply. Is this a problem with a path locally on my install? Or a general bug in the library?

**Comment by dalerank** [comment]
look at file path which finds, and where exe placed, possible work directory is wrong

**Comment by Andy608** [comment]
Whoops! It was my fault. I wasn't including the correct vulkan header files. Everything seems to be working now except for example4.cpp where it says wrong backend.
